<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/11/27 00:50:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'toor',
  'name' => 'doctrine',
)),);
